env: local 

logger:
  level: "info"
  destination: "./api/logs/local"
  channel: "daily"

http:
  port: ":8080"
  maxHeaderBytes: 1
  readTimeout: "10s"
  writeTimeout: "10s"

db:
  dsn: "postgres://admin:admin@localhost:5432/db?sslmode=disable"

auth:
  accessTokenTTL: 2h
  refreshTokenTTL: 720h #30 days

